### ISSUE TITLE
complaints disposal

### ISSUE THREAD

**Issue by sandeep4212** [ranvirp/basicuser#4]
Respected Sir,
                      sadar avagat karana hai ki jab vibhag ki aakhya approve karte hai to yadi wah report kisi aur dept. ko bhejni hoti hai to us dept. ko assingned kar dete hai. phir bhi wah report approve box se nahi jati hai. jisse problem aa rahi hai. pls issue ko solve karne ki kripa karin. sir likhne me yadi koi galti ho gai ho to chama karne ki kripa kariyega.

yours obidient
sandeep srivastava
complain cleark
azamgarh.

**Comment by ranvirp** [comment]
please attach a screenshot with pointers showing the problem area.

**Comment by ranvirp** [comment]
It should be fixed. Attempt git pull origin master from dmoffice folder. And create issues in dmoffice and not in basicuser.
